version: '3.8'

services:
  frontend:
    build:
      context: ./React2/myapp
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mynetwork

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      - mynetwork

networks:
  mynetwork:
