name: CI/CD Pipeline Update

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker images
      run: docker-compose -f docker-compose.yml build

    - name: Run Docker containers
      run: docker-compose -f docker-compose.yml up -d

    - name: Run frontend tests
      run: |
        # Uncomment the following line to run frontend tests
        # docker exec docker_fyp_frontend_1 npm test -- --coverage

    - name: Run backend tests
      run: |
        # Uncomment the following line to run backend tests
        # docker exec docker_fyp_backend_1 pytest --rootdir=/app/backend

    - name: Shut down Docker containers
      run: docker-compose -f docker-compose.yml down

  cd:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Push Docker images to Docker Hub
      run: |
        docker tag fyp_devops_practice_frontend:latest wadeed/fyp_devops_practice_frontend:latest
        docker tag fyp_devops_practice_backend:latest wadeed/fyp_devops_practice_backend:latest
        docker push wadeed/fyp_devops_practice_frontend:latest
        docker push wadeed/fyp_devops_practice_backend:latest

    - name: Set up Minikube
      uses: manusa/actions-setup-minikube@v2.5.0
      with:
        minikube version: 'latest'
        start: true
        driver: docker

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment.yml
        kubectl apply -f k8s/service.yml
