name: CI/CD Pipeline Update

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker images
      run: |
        docker build -t wadeed/fyp_1:v1 React2/myapp
        docker build -t wadeed/fyp_1:v2 Backend

    - name: Run frontend tests
      run: |
        # Uncomment the following lines to run frontend tests
        # docker run --rm -it wadeed/fyp_1:v1 npm test -- --coverage

    - name: Run backend tests
      run: |
        # Uncomment the following lines to run backend tests
        # docker run --rm -it wadeed/fyp_1:v2 pytest --rootdir=/app/backend

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker images to Docker Hub
      run: |
        docker push wadeed/fyp_1:v1
        docker push wadeed/fyp_1:v2

  cd:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Pull Docker images from Docker Hub
      run: |
        docker pull wadeed/fyp_1:v1
        docker pull wadeed/fyp_1:v2

    - name: Scan Docker images with Trivy
      run: |
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image wadeed/fyp_1:v1
        docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy image wadeed/fyp_1:v2

    - name: Set up Minikube
      uses: manusa/actions-setup-minikube@v2.5.0
      with:
        minikube version: 'latest'
        start: true
        driver: docker

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment.yml
        kubectl apply -f k8s/service.yml
        kubectl get deployments
