name: CI/CD Pipeline Update

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker images
      run: docker-compose -f docker-compose.yml build

    - name: Run frontend tests
      run: |
        # Uncomment the following line to run frontend tests
        # docker-compose -f docker-compose.yml run frontend npm test -- --coverage

    - name: Run backend tests
      run: |
        # Uncomment the following line to run backend tests
        # docker-compose -f docker-compose.yml run backend pytest --rootdir=/app/backend

    - name: Tag Docker images
      run: |
        docker tag $(docker images -q frontend) wadeed/fyp_1:frontend
        docker tag $(docker images -q backend) wadeed/fyp_1:backend

  cd:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Docker images to Docker Hub
      run: |
        docker push wadeed/fyp_1:frontend
        docker push wadeed/fyp_1:backend

    - name: Set up Minikube
      uses: manusa/actions-setup-minikube@v2.5.0
      with:
        minikube version: 'latest'
        start: true
        driver: docker

    - name: Deploy to Minikube
      run: |
        kubectl apply -f k8s/deployment.yml
        kubectl apply -f k8s/service.yml
